global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ["api:8000"]     

  - job_name: minio
    metrics_path: /minio/v2/metrics/node
    static_configs:
      - targets: ["minio:9000"]    
